Disalbe _build_id_links
install gpdb server rhel8 rpm on gcr.io/data-gpdb-private-images/gpdb6-rhel8-build image will cause fowllowing errors
Error: Transaction test error file /usr/lib/.build-id/e2/27e93b07fbc71d773fa0bb847faba619639bb4 from install of greenplum-db-6-6.20.0-1.el8.x86_64 conflicts with file from package libquicklz-1.5.0-1.el8.x86_64 file /usr/lib/.build-id/e1/912a5ed956a4243112da62fc86e62cc0176512 from install of greenplum-db-6-6.20.0-1.el8.x86_64 conflicts with file from package libzstd-1.3.7-2.el8.x86_64

So disable build_id_links to bypass the error

[GPR-747]

Authored-by: Shaoqi Bai <bshaoqi@vmware.com>