call subsription-manager before greenplum-path.sh
Or else pythonhome is set to python2, and will see error
+ subscription-manager remove --all
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Authored-by: Shaoqi Bai <bshaoqi@vmware.com>